export const WEDDING_INVITATION_ASSETS = {
  heroBackground: "/assets/wedding-invitation/hero-background-mountains.png",
  heroCouplePhoto: "/assets/wedding-invitation/hero-couple-photo.png",
  heroGrassForeground: "/assets/wedding-invitation/hero-grass-foreground.png",
  meadowFlowerDivider: "/assets/wedding-invitation/meadow-flower-divider.png",
  countdownCardDecor: "/assets/wedding-invitation/countdown-card-decor.png",
  tallGrassDivider: "/assets/wedding-invitation/tall-grass-divider.png",
  envelopeBackPanel: "/assets/wedding-invitation/envelope-back-panel.png",
  envelopeMeadowFlap: "/assets/wedding-invitation/envelope-meadow-flap.png",
  envelopeFrontPanel: "/assets/wedding-invitation/envelope-front-panel.png",
  floralBouquetLeft: "/assets/wedding-invitation/floral-bouquet-left.png",
  envelopeGreenHillTransition: "/assets/wedding-invitation/envelope-green-hill-transition.png",
  waxSealGold: "/assets/wedding-invitation/wax-seal-gold.png",
  envelopePaperCard: "/assets/wedding-invitation/envelope-paper-card.png",
  groomPhotoWilliam: "/assets/wedding-invitation/groom-photo-william.png",
  stampFrame: "/assets/wedding-invitation/stamp-frame.png",
  bridePhotoAziel: "/assets/wedding-invitation/bride-photo-aziel.png",
  floralBouquetRight: "/assets/wedding-invitation/floral-bouquet-right.png",
  saveDateGoldBadge: "/assets/wedding-invitation/save-date-gold-badge.png",
  tornDatePaper: "/assets/wedding-invitation/torn-date-paper.png",
  holyMatrimonyIllustration: "/assets/wedding-invitation/holy-matrimony-illustration.png",
  receptionDinnerIllustration: "/assets/wedding-invitation/reception-dinner-illustration.png",
  daisyGardenDivider: "/assets/wedding-invitation/daisy-garden-divider.png",
  galleryPlaceholder: "/assets/wedding-invitation/gallery-placeholder.png",
  footerMeadowHills: "/assets/wedding-invitation/footer-meadow-hills.png",
  textareaResizeGrab: "/assets/wedding-invitation/textarea-resize-grab.svg",
} as const;
