import type { EventType, EventSession, RsvpStatus } from "@/lib/constants";

// ─── Database Autogenerated Placeholder ─────────────────────────────────────
// This file will be replaced by the Supabase-generated types in Phase 2.
// Keep it here so the Supabase clients compile now.
export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views:  Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};

// ─── Domain Types ─────────────────────────────────────────────────────────────

export interface Guest {
  id:         string;
  name:       string;
  phone:      string | null;
  email:      string | null;
  notes:      string | null;
  created_at: string;
  updated_at: string;
}

export interface Invitation {
  id:          string;
  code:        string;           // unique invite code
  event_type:  EventType;
  guest_id:    string;
  guest_name:  string;           // denormalised for quick display
  is_active:   boolean;
  created_at:  string;
  updated_at:  string;
  // relations
  guest?:      Guest;
  events?:     InvitationEvent[];
  rsvp?:       Rsvp | null;
}

export interface InvitationEvent {
  id:            string;
  invitation_id: string;
  session:       EventSession;
  date:          string;         // "YYYY-MM-DD"
  time_start:    string;         // "HH:mm:ss"
  time_end:      string | null;
  venue_name:    string;
  venue_address: string;
  venue_maps_url:string | null;
  created_at:    string;
}

export interface Rsvp {
  id:            string;
  invitation_id: string;
  status:        RsvpStatus;
  attending_count: number;
  dietary_notes: string | null;
  message:       string | null;
  submitted_at:  string;
  updated_at:    string;
}

export interface SeatingArrangement {
  id:            string;
  invitation_id: string;
  session:       EventSession;
  table_number:  string | null;
  seat_number:   string | null;
  notes:         string | null;
  created_at:    string;
  updated_at:    string;
}

export interface Settings {
  id:                  string;
  wedding_date:        string | null;
  sangjit_date:        string | null;
  couple_names:        string;
  groom_name:          string;
  bride_name:          string;
  cover_image_url:     string | null;
  instagram_handle:    string | null;
  bank_name:           string | null;
  bank_account:        string | null;
  bank_account_holder: string | null;
  updated_at:          string;
}

// ─── API / UI helpers ────────────────────────────────────────────────────────

export type ApiResponse<T> =
  | { data: T; error: null }
  | { data: null; error: string };

export type PaginatedResponse<T> = {
  data:  T[];
  total: number;
  page:  number;
  limit: number;
};

export type InvitationWithDetails = Invitation & {
  guest:  Guest;
  events: InvitationEvent[];
  rsvp:   Rsvp | null;
  seating: SeatingArrangement[];
};
