import { Database } from "./database";

// Re-export the autogenerated Database type
export type { Database } from "./database";

// ─── Extracted Supabase Row Types ──────────────────────────────────────────
export type EventType = Database["public"]["Tables"]["event_types"]["Row"];
export type EventSession = Database["public"]["Tables"]["event_sessions"]["Row"];
export type Guest = Database["public"]["Tables"]["guests"]["Row"];
export type Invitation = Database["public"]["Tables"]["invitations"]["Row"];
export type Rsvp = Database["public"]["Tables"]["rsvps"]["Row"];
export type RsvpSelectedSession = Database["public"]["Tables"]["rsvp_selected_sessions"]["Row"];
export type SeatingTable = Database["public"]["Tables"]["seating_tables"]["Row"];
export type SeatingAssignment = Database["public"]["Tables"]["seating_assignments"]["Row"];
export type GalleryImage = Database["public"]["Tables"]["gallery_images"]["Row"];
export type Settings = Database["public"]["Tables"]["settings"]["Row"];

// ─── Enums ────────────────────────────────────────────────────────────────
export type GuestCategory = Database["public"]["Enums"]["guest_category"];
export type GuestOwner = Database["public"]["Enums"]["guest_owner"];
export type AttendanceStatus = Database["public"]["Enums"]["attendance_status"];

// ─── API / UI helpers ────────────────────────────────────────────────────────
export type ApiResponse<T> =
  | { data: T; error: null }
  | { data: null; error: string };

export type PaginatedResponse<T> = {
  data: T[];
  total: number;
  page: number;
  limit: number;
};

// Represents a full invitation loaded with relations
export type InvitationWithDetails = Invitation & {
  guest?: Guest;
  event_type?: EventType;
  rsvp?: Rsvp | null;
  seating_assignment?: (SeatingAssignment & { seating_table?: SeatingTable }) | null;
};
